In [1]:
print('Hello, World!!')

Hello, World!!


In [2]:
print('하하하')

하하하


In [10]:
import numpy as np

data = np.random.rand(3, 4)
print(data)

list = [3, 4.1, 5, 6.3, 7, 8.6] #단일 리스트
arr = np.array(list)

print('평균', arr.mean())
print('합계', arr.sum())
print('최대값', arr.max())
print('최소값', arr.min())
print('분산', arr.var())
print('표준편차', arr.std())

list = [ [9,8,7,6,5] , [1,2,3,4,5] ] #중첩리스트
arr = np.array(list)
print(arr)
print(arr[0,2])
print(arr[1,3])
print(arr[0,:])
print(arr[:,1])

#자동으로 채워지는 행렬 생성
zarr = np.zeros((3,5))      #0으로 채워지는 3x5행렬 생성
print(zarr)

#정수 생성
cnt = 0
for i in np.arange(3):
    for j in np.arange(5):
        cnt += 1
        zarr[i, j] = cnt

print(zarr)
#외부 csv파일 읽어 배열 생성
phone = np.genfromtxt('c:/Java/phone-01.csv',delimiter=',')  #텍스트파일을 배열로 생성
print(phone)
print(np.mean(phone[:,2]))  #화면크기 항목에 대한 평균 출력
print(np.median(phone[:,2]))  #중앙값

print('총 개수 : ', len(phone))

p_col3 = phone[:,2]
print(np.percentile(p_col3, 0))   #사분위값 : 최소값
print(np.percentile(p_col3, 25))  #1사분위값
print(np.percentile(p_col3, 50))  #2사분위값
print(np.percentile(p_col3, 75))  #3사분위값
print(np.percentile(p_col3, 100)) #사분위값 : 최대값

#scipy에는 여러가지 기술통계를 한번에 계산해주는
#describe 함수가 있음
from scipy.stats import describe
print(describe(phone))


[[0.56845697 0.852327   0.48810619 0.83645915]
 [0.72364395 0.60399938 0.18862452 0.08564604]
 [0.67114817 0.47239308 0.42585013 0.68566041]]
평균 5.666666666666667
합계 34.0
최대값 8.6
최소값 3.0
분산 3.465555555555555
표준편차 1.8616002673924268
[[9 8 7 6 5]
 [1 2 3 4 5]]
7
4
[9 8 7 6 5]
[8 2]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]]
[[2015.  2015.     5. ]
 [2014.  2015.     4.5]
 [2015.  2015.     5. ]
 [2015.  2016.     5. ]
 [2015.  2015.     5. ]
 [2016.  2016.     5.5]
 [2016.  2016.     6. ]
 [2014.  2014.     5. ]
 [2014.  2014.     4.5]
 [2015.  2014.     5. ]
 [2014.  2015.     4.5]
 [2015.  2015.     5.5]
 [2015.  2016.     5.5]
 [2015.  2015.     6. ]
 [2015.  2015.     5.5]
 [2015.  2015.     5. ]
 [2016.  2016.     5.5]
 [2016.  2016.     6. ]
 [2015.  2015.     4.5]
 [2016.  2016.     5.5]
 [2015.  2015.     5.5]
 [2016.  2016.     5.5]
 [2015.  2015.     5. ]
 [2016.  2016.     6. ]]
5.25
5.25
총 개수 : 

KeyError: '[85.5  61.   84.5  86.5  71.5  85.25 68.75 85.75 74.75 90.5  63.25 79.75] not in index'